# Generated by Django 5.1.2 on 2024-11-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0025_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
