# Generated by Django 5.1.2 on 2024-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0027_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
